[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "crowd-code-player"
version = "0.1.0"
description = "A crowd code player application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.0.0",
]